 <main class="loginFond">
     <div id="container">
         <!-- zone de connexion -->

         <form action="login.php" method="POST">
             <h1>Connexion</h1>
             <p><?php
                echo $alert; ?></p>
             <div>
                 <label for="firstname">Nom d'utilisateur</label>
                 <input type="text" placeholder="Entrer le nom d'utilisateur" id="firstname" name="login" required>
             </div>
             <div>
                 <label for="lastname">Mot de passe</label>
                 <input type="password" placeholder="Entrer le mot de passe" id="lastname" name="password" required>
             </div>
             <input type="submit" id='submit' class="submit" value='login'>
         </form>
     </div>
 </main>