<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>RE_ : Dev</title>
    <link rel="stylesheet" href="../css/style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" charset="utf-8"></script>
  </head>
  <body>
    <!--checkbox and boutton sidebar-->
    <input type="checkbox" id="check">

    <!-- header area start-->
    <header>
      <!--checkbox and boutton sidebar-->
      <label for="check">
        <i class="fas fa-bars" id="sidebar_btn"></i>
      </label>
      <!--logo of site -->
       <div class="left_area">
        <h3>RE : <span>Dev</span></h3>
      </div>
      <dev class="right_area">
        <a href="#" class="logout_btn">Logout</a>
      </dev>
    </header>
    <!-- header area end-->

    <!--mobile navigation bar start-->
    <div class="mobile_nav">
      <div class="nav_bar">
        <img src="../img/roody.png" class="mobile_profile_img" alt="photo de profile">
        <i class="fa fa-bars nav_btn"></i>
      </div>
    </div>
    <div class="mobile_nav_items">
      <a href="# " ><i class="fas fa-desktop"></i><span>Dashboard</span></a>
      <a href="#" ><i class="fas fa-cogs"></i><span>Skills</span></a>
      <a href="#" ><i class="fas fa-th"></i><span>porfollio</span></a>
      <a href="#" ><i class="fas fa-info-circle"></i><span>Abouts</span></a>
      <a href="#" ><i class="fas fa-sliders-h"></i><span>Setting</span></a>
    </div>
    <!--mobile navigation bar end-->

    <!--sidebar start-->
    <div class="sidebar">
      <div class="profile_info">
        <img src="../img/roody.png" class="profile_image" alt="photo de profile">
        <h4>Roody Exantus</h4>
      <!--the intems on navigation start-->
      </div>
      <a href="# " ><i class="fas fa-desktop"></i><span>Dashboard</span></a>
      <a href="#" ><i class="fas fa-cogs"></i><span>Skills</span></a>
      <a href="#" ><i class="fas fa-th"></i><span>porfollio</span></a>
      <a href="../cv/index.html" ><i class="fas fa-info-circle"></i><span>Abouts</span></a>
      <a href="#" ><i class="fas fa-sliders-h"></i><span>Setting</span></a>
    </div>
    <!--the intems on navigation start-->
    <!--sidebar end-->




    <div class="content">
      <div class="card">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      </div>

      <div class="card">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      </div>

      <div class="card">
        <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
      </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function () {
        $('.nav_btn').click(function () {
          $('.mobile_nav_items').toggleClass('active');
        });
      });
    </script>
  </body>
</html>
